using System.Text;

namespace CSharpRoll.Core;

/// <summary>
/// Writes rolled output file by concatenating source files with separators.
/// </summary>
public static class RollWriter
{
    /// <summary>
    /// Writes rolled output to disk.
/// </summary>
    public static void Write(
        string outputPath,
        IReadOnlyList<string> files,
        string rootDir,
        IReadOnlyList<string> projectNames,
        RollOptions options)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);

        using var stream = new FileStream(outputPath, FileMode.Create, FileAccess.Write, FileShare.Read);
        using var writer = new StreamWriter(stream, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        var now = DateTimeOffset.Now;

        if (options.Format == OutputFormat.CSharp)
        {
            writer.WriteLine("// <auto-generated>");
            writer.WriteLine($"// Rolled by CSharpRoll at {now:O}");
            writer.WriteLine($"// Projects: {string.Join(", ", projectNames)}");
            writer.WriteLine("// </auto-generated>");
            writer.WriteLine();
        }
        else
        {
            writer.WriteLine($"# CSharpRoll output ({now:O})");
            writer.WriteLine();
            writer.WriteLine($"- Projects: {string.Join(", ", projectNames)}");
            writer.WriteLine($"- Files: {files.Count}");
            writer.WriteLine();
        }

        foreach (var file in files)
        {
            var rel = Path.GetRelativePath(rootDir, file);

            if (options.Format == OutputFormat.Markdown)
            {
                writer.WriteLine($"## {rel}");
                writer.WriteLine();
                writer.WriteLine("```csharp");
                writer.WriteLine($"// ===== File: {rel} =====");
            }
            else
            {
                writer.WriteLine($"// ===== BEGIN FILE: {rel} =====");
            }

            WriteFileBody(writer, file);

            if (options.Format == OutputFormat.Markdown)
            {
                writer.WriteLine("```");
                writer.WriteLine();
            }
            else
            {
                writer.WriteLine();
                writer.WriteLine($"// ===== END FILE: {rel} =====");
                writer.WriteLine();
            }
        }
    }

    private static void WriteFileBody(TextWriter writer, string filePath)
    {
        string text;
        try
        {
            text = File.ReadAllText(filePath, new UTF8Encoding(false, true));
        }
        catch
        {
            text = File.ReadAllText(filePath);
        }

        text = text.Replace("\r\n", "\n").Replace("\r", "\n");
        writer.WriteLine(text.TrimEnd('\n'));
    }
}