using System.Text;

namespace CSharpRoll.Core;

/// <summary>
/// Writes rolled output file by concatenating project csproj (raw) and source files with separators.
/// </summary>
public static class RollWriter
{
    public static void Write(
        string outputPath,
        IReadOnlyList<RolledProject> projects,
        string rootDir,
        RollOptions options)
    {
        var outDir = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrWhiteSpace(outDir))
            Directory.CreateDirectory(outDir);

        var filePathComparer = OperatingSystem.IsWindows()
            ? StringComparer.OrdinalIgnoreCase
            : StringComparer.Ordinal;

        // total unique file count across all projects (for header)
        var allUnique = new HashSet<string>(filePathComparer);
        foreach (var p in projects)
        foreach (var f in p.Files)
            allUnique.Add(f);

        using var stream = new FileStream(outputPath, FileMode.Create, FileAccess.Write, FileShare.Read);
        using var writer = new StreamWriter(stream, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        var now = DateTimeOffset.Now;
        var projectNames = projects.Select(p => p.Name).ToList();

        if (options.Format == OutputFormat.CSharp)
        {
            writer.WriteLine("// <auto-generated>");
            writer.WriteLine($"// Rolled by CSharpRoll at {now:O}");
            writer.WriteLine($"// Projects: {string.Join(", ", projectNames)}");
            writer.WriteLine($"// Files: {allUnique.Count}");
            writer.WriteLine("// </auto-generated>");
            writer.WriteLine();
        }
        else
        {
            writer.WriteLine($"# CSharpRoll output ({now:O})");
            writer.WriteLine();
            writer.WriteLine($"- Projects: {string.Join(", ", projectNames)}");
            writer.WriteLine($"- Files: {allUnique.Count}");
            writer.WriteLine();
        }

        // global dedupe: linked/shared files across projects are written once
        var writtenFiles = new HashSet<string>(filePathComparer);

        foreach (var project in projects)
        {
            WriteProjectHeader(writer, project, options);

            foreach (var file in project.Files)
            {
                if (!writtenFiles.Add(file))
                    continue;

                var rel = Path.GetRelativePath(rootDir, file);

                if (options.Format == OutputFormat.Markdown)
                {
                    writer.WriteLine($"### {rel}");
                    writer.WriteLine();
                    writer.WriteLine("```csharp");
                    writer.WriteLine($"// ===== File: {rel} =====");
                }
                else
                {
                    writer.WriteLine($"// ===== BEGIN FILE: {rel} =====");
                }

                WriteFileBody(writer, file);

                if (options.Format == OutputFormat.Markdown)
                {
                    writer.WriteLine("```");
                    writer.WriteLine();
                }
                else
                {
                    writer.WriteLine();
                    writer.WriteLine($"// ===== END FILE: {rel} =====");
                    writer.WriteLine();
                }
            }
        }
    }

    private static void WriteProjectHeader(TextWriter writer, RolledProject project, RollOptions options)
    {
        if (options.Format == OutputFormat.CSharp)
        {
            writer.WriteLine($"// ===== PROJECT: {project.Name} =====");
            writer.WriteLine($"// Path: {project.CsprojPath}");
            writer.WriteLine("// ----- .csproj (raw) -----");
            foreach (var line in SplitLines(project.CsprojRaw))
                writer.WriteLine("// " + line);
            writer.WriteLine("// ----- end .csproj (raw) -----");
            writer.WriteLine();
        }
        else
        {
            writer.WriteLine($"## Project: {project.Name}");
            writer.WriteLine();
            writer.WriteLine($"- Path: `{project.CsprojPath}`");
            writer.WriteLine($"- Files: `{project.Files.Count}`");
            writer.WriteLine();
            writer.WriteLine("```xml");
            writer.WriteLine(project.CsprojRaw.TrimEnd());
            writer.WriteLine("```");
            writer.WriteLine();
        }
    }

    private static IEnumerable<string> SplitLines(string text)
    {
        text = text.Replace("\r\n", "\n").Replace("\r", "\n");
        return text.Split('\n');
    }

    private static void WriteFileBody(TextWriter writer, string filePath)
    {
        string text;
        try
        {
            text = File.ReadAllText(filePath, new UTF8Encoding(false, true));
        }
        catch
        {
            text = File.ReadAllText(filePath);
        }

        text = text.Replace("\r\n", "\n").Replace("\r", "\n");
        writer.WriteLine(text.TrimEnd('\n'));
    }
}
